% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Apr-2019 11:55:28
%  MATLAB version: 9.5.0.944444 (R2018b)
% -------------------------------------------------------------------

%gets the data table
saveVarsMat = load('app.mat');
data = saveVarsMat.data; % <1x1 table> unsupported class
%gets the labels for the data arows
labels = table2array(data(:,16));

%gets unique labels of all data set
unqiueLabels = unique(labels);

%removes the Parameters that won't be used as mentioned in the
%documentation
arr = table2array([data(:,1:4),data(:,7:10)]);



%gets the labels for the picked sample
UniqueLabels = unqiueLabels(1:14);

%gets the indexes for the pciked sample labels
Indexs = find(ismember(labels,UniqueLabels));

%gets all labels for the picked dataset
dataLabels = labels(Indexs);

%data summary of picked sample
dataSummary=summary(data(Indexs,:));

% gets the data parameters for the picked sample
dataArray = arr(Indexs,:);



% plotMatrix=[answerMean;shopMean;hotMean];
clear arr;
clear saveVarsMat;
% bar(plotMatrix,'DisplayName','plotMatrix')